name: Build & Push Frontend

on:
  push:
    branches: [ main ]

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - run: |
          npm ci
          npm run build

      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/com2here/com2here_front:latest

